# Generated by Django 3.1.3 on 2020-11-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.FloatField(default=0, max_length=1000),
        ),
    ]
