# Generated by Django 3.1.3 on 2020-11-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='down_count',
            field=models.FloatField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='up_count',
            field=models.FloatField(default=0, max_length=1000),
        ),
    ]
